"""Add inference and upload models

Revision ID: 37bfd0726357
Revises: 20f912b3ae3d
Create Date: 2026-07-05 19:41:29.972757
"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = "37bfd0726357"
down_revision: str | None = "20f912b3ae3d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "inference_jobs",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("job_id", sa.String(), nullable=False),
        sa.Column("idempotency_key", sa.String(), nullable=True),
        sa.Column("user_id", sa.String(), nullable=True),
        sa.Column("status", sa.String(), nullable=True),
        sa.Column("study_metadata", sa.JSON(), nullable=True),
        sa.Column("model_versions", sa.JSON(), nullable=True),
        sa.Column("final_result", sa.JSON(), nullable=True),
        sa.Column("progress", sa.JSON(), nullable=True),
        sa.Column("error_message", sa.String(), nullable=True),
        sa.Column("retry_count", sa.Integer(), nullable=True),
        sa.Column("api_version", sa.String(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_inference_jobs_created_at"), "inference_jobs", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_inference_jobs_idempotency_key"),
        "inference_jobs",
        ["idempotency_key"],
        unique=False,
    )
    op.create_index(op.f("ix_inference_jobs_job_id"), "inference_jobs", ["job_id"], unique=True)
    op.create_index(op.f("ix_inference_jobs_status"), "inference_jobs", ["status"], unique=False)
    op.create_index(op.f("ix_inference_jobs_user_id"), "inference_jobs", ["user_id"], unique=False)
    op.create_index(
        "ix_user_idempotency", "inference_jobs", ["user_id", "idempotency_key"], unique=True
    )
    op.create_table(
        "upload_records",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("upload_id", sa.String(), nullable=False),
        sa.Column("filename", sa.String(), nullable=False),
        sa.Column("status", sa.String(), nullable=True),
        sa.Column("user_id", sa.String(), nullable=True),
        sa.Column("storage_path", sa.String(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_upload_records_created_at"), "upload_records", ["created_at"], unique=False
    )
    op.create_index(op.f("ix_upload_records_status"), "upload_records", ["status"], unique=False)
    op.create_index(
        op.f("ix_upload_records_upload_id"), "upload_records", ["upload_id"], unique=True
    )
    op.create_index(op.f("ix_upload_records_user_id"), "upload_records", ["user_id"], unique=False)
    op.create_table(
        "users",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("hashed_password", sa.String(length=255), nullable=False),
        sa.Column("full_name", sa.String(length=255), nullable=False),
        sa.Column("role", sa.String(length=50), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_table(
        "audit_logs",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=True),
        sa.Column("action", sa.String(length=100), nullable=False),
        sa.Column("resource_type", sa.String(length=100), nullable=False),
        sa.Column("resource_id", sa.String(length=255), nullable=True),
        sa.Column("details", postgresql.JSON(astext_type=sa.Text()), nullable=True),
        sa.Column("ip_address", sa.String(length=45), nullable=True),
        sa.Column("user_agent", sa.String(length=500), nullable=True),
        sa.Column("correlation_id", sa.String(length=100), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_audit_logs_action", "audit_logs", ["action"], unique=False)
    op.create_index(op.f("ix_audit_logs_created_at"), "audit_logs", ["created_at"], unique=False)
    op.create_index("ix_audit_logs_user_id", "audit_logs", ["user_id"], unique=False)
    op.create_table(
        "patients",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("medical_record_number", sa.String(length=100), nullable=False),
        sa.Column("full_name", sa.String(length=255), nullable=False),
        sa.Column("date_of_birth", sa.Date(), nullable=True),
        sa.Column("gender", sa.String(length=20), nullable=True),
        sa.Column("referring_physician", sa.String(length=255), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("created_by", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("version_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_patients_created_at"), "patients", ["created_at"], unique=False)
    op.create_index(op.f("ix_patients_is_deleted"), "patients", ["is_deleted"], unique=False)
    op.create_index(
        op.f("ix_patients_medical_record_number"),
        "patients",
        ["medical_record_number"],
        unique=False,
    )
    op.create_index(
        "ix_patients_medical_record_number_not_deleted",
        "patients",
        ["medical_record_number"],
        unique=True,
        postgresql_where="(is_deleted IS FALSE)",
    )
    op.create_table(
        "studies",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("patient_id", sa.UUID(), nullable=False),
        sa.Column("study_type", sa.String(length=50), nullable=False),
        sa.Column("modality", sa.String(length=50), nullable=True),
        sa.Column("file_path", sa.String(length=500), nullable=False),
        sa.Column("file_size_bytes", sa.BigInteger(), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("uploaded_by", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("version_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["patient_id"], ["patients.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["uploaded_by"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_studies_created_at"), "studies", ["created_at"], unique=False)
    op.create_index(op.f("ix_studies_is_deleted"), "studies", ["is_deleted"], unique=False)
    op.create_index("ix_studies_patient_id", "studies", ["patient_id"], unique=False)
    op.create_table(
        "predictions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("study_id", sa.UUID(), nullable=False),
        sa.Column("model_version", sa.String(length=50), nullable=False),
        sa.Column("prediction_class", sa.String(length=100), nullable=True),
        sa.Column("confidence", sa.Float(), nullable=True),
        sa.Column("processing_time_ms", sa.Integer(), nullable=True),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("requested_by", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("version_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["requested_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(["study_id"], ["studies.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_predictions_created_at"), "predictions", ["created_at"], unique=False)
    op.create_index(op.f("ix_predictions_is_deleted"), "predictions", ["is_deleted"], unique=False)
    op.create_index("ix_predictions_status", "predictions", ["status"], unique=False)
    op.create_index("ix_predictions_study_id", "predictions", ["study_id"], unique=False)
    op.create_table(
        "segmentation_results",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("study_id", sa.UUID(), nullable=False),
        sa.Column("prediction_id", sa.UUID(), nullable=True),
        sa.Column("model_version", sa.String(length=50), nullable=False),
        sa.Column("mask_path", sa.String(length=500), nullable=True),
        sa.Column("tumor_volume_mm3", sa.Float(), nullable=True),
        sa.Column("dice_score", sa.Float(), nullable=True),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("requested_by", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("version_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["prediction_id"], ["predictions.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(
            ["requested_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(["study_id"], ["studies.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_segmentation_results_created_at"),
        "segmentation_results",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_segmentation_results_is_deleted"),
        "segmentation_results",
        ["is_deleted"],
        unique=False,
    )
    op.create_index(
        "ix_segmentation_results_prediction_id",
        "segmentation_results",
        ["prediction_id"],
        unique=False,
    )
    op.create_index(
        "ix_segmentation_results_study_id", "segmentation_results", ["study_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_segmentation_results_study_id", table_name="segmentation_results")
    op.drop_index("ix_segmentation_results_prediction_id", table_name="segmentation_results")
    op.drop_index(op.f("ix_segmentation_results_is_deleted"), table_name="segmentation_results")
    op.drop_index(op.f("ix_segmentation_results_created_at"), table_name="segmentation_results")
    op.drop_table("segmentation_results")
    op.drop_index("ix_predictions_study_id", table_name="predictions")
    op.drop_index("ix_predictions_status", table_name="predictions")
    op.drop_index(op.f("ix_predictions_is_deleted"), table_name="predictions")
    op.drop_index(op.f("ix_predictions_created_at"), table_name="predictions")
    op.drop_table("predictions")
    op.drop_index("ix_studies_patient_id", table_name="studies")
    op.drop_index(op.f("ix_studies_is_deleted"), table_name="studies")
    op.drop_index(op.f("ix_studies_created_at"), table_name="studies")
    op.drop_table("studies")
    op.drop_index(
        "ix_patients_medical_record_number_not_deleted",
        table_name="patients",
        postgresql_where="(is_deleted IS FALSE)",
    )
    op.drop_index(op.f("ix_patients_medical_record_number"), table_name="patients")
    op.drop_index(op.f("ix_patients_is_deleted"), table_name="patients")
    op.drop_index(op.f("ix_patients_created_at"), table_name="patients")
    op.drop_table("patients")
    op.drop_index("ix_audit_logs_user_id", table_name="audit_logs")
    op.drop_index(op.f("ix_audit_logs_created_at"), table_name="audit_logs")
    op.drop_index("ix_audit_logs_action", table_name="audit_logs")
    op.drop_table("audit_logs")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    op.drop_index(op.f("ix_upload_records_user_id"), table_name="upload_records")
    op.drop_index(op.f("ix_upload_records_upload_id"), table_name="upload_records")
    op.drop_index(op.f("ix_upload_records_status"), table_name="upload_records")
    op.drop_index(op.f("ix_upload_records_created_at"), table_name="upload_records")
    op.drop_table("upload_records")
    op.drop_index("ix_user_idempotency", table_name="inference_jobs")
    op.drop_index(op.f("ix_inference_jobs_user_id"), table_name="inference_jobs")
    op.drop_index(op.f("ix_inference_jobs_status"), table_name="inference_jobs")
    op.drop_index(op.f("ix_inference_jobs_job_id"), table_name="inference_jobs")
    op.drop_index(op.f("ix_inference_jobs_idempotency_key"), table_name="inference_jobs")
    op.drop_index(op.f("ix_inference_jobs_created_at"), table_name="inference_jobs")
    op.drop_table("inference_jobs")
    # ### end Alembic commands ###
